### ISSUE TITLE
Optionnally prevent automatic index group selection

### ISSUE THREAD

**Issue by jbarnoud** [mnmelo/MDreader#2]
If an index file is read with the add_ndx method, and that index file contains the number of groups that is expected, then the interactive selection process is skipped and all the groups are read. This is extremely convenient when the order of the groups does not matter. When the order of the groups does matter, though, it can be surprising and lead to mistakes.

Maybe there could be a flag (in the command line or in the API, I do not know at what level it should be), to prevent MDreader to automatically select the groups.

**Comment by mnmelo** [comment]
Yup, there's a flag. Just pass `smartindex=False` to `add_ndx()`:

**Comment by jbarnoud** [comment]
Haven't seen it. Thanks.
